name: Rollback Widget
description: Roll back widget to a specific version if the asset exists on CDN.

inputs:
  target-version:
    description: "Version to roll back to"
    required: true
  environment:
    description: "Target environment (integration or production)"
    required: true
  caller-repo:
    description: "The full name of the caller repo"
    required: true
  caller-repo-ref:
    description: "Git ref (branch, tag, or SHA) of the caller repo"
    required: true
  AZURE_APP_CONFIG_CONNECTION_STRING:
    description: "Azure App Config connection string"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Caller Repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.caller-repo }}
        ref: ${{ inputs.caller-repo-ref }}
        fetch-depth: 1

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "yarn"

    - name: Get Widget ID from package.json
      id: get_widget_id
      shell: bash
      run: |
        echo "widgetId=$(npm pkg get name | tr -d '"')" >> $GITHUB_OUTPUT

    - name: Check CDN for Rollback Asset
      id: check_cdn
      shell: bash
      env:
        WIDGET_ID: ${{ steps.get_widget_id.outputs.widgetId }}
        TARGET_VERSION: ${{ inputs.target-version }}
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        CDN_BASE_URL="https://1fe-a.akamaihd.net"
        if [[ "$ENVIRONMENT" == "integration" ]]; then
          CDN_PATH="integration"
        elif [[ "$ENVIRONMENT" == "production" ]]; then
          CDN_PATH="production"
        else
          echo "Invalid environment: $ENVIRONMENT"
          exit 1
        fi

        BUNDLE_URL="${CDN_BASE_URL}/${CDN_PATH}/widgets/$WIDGET_ID/$TARGET_VERSION/js/1fe-bundle.js"
        echo "Checking CDN for: $BUNDLE_URL"

        HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$BUNDLE_URL")
        echo "HTTP Status: $HTTP_STATUS"

        if [[ "$HTTP_STATUS" -ne 200 ]]; then
          echo "Asset not found on CDN. Exiting."
          exit 1
        fi

    - name: Update Azure App Config
      uses: docusign/1fe-ci-cd/.github/actions/update-azure-config@main
      with:
        environment: ${{ inputs.environment }}
        widgetId: ${{ steps.get_widget_id.outputs.widgetId }}
        nextVersion: ${{ inputs.target-version }}
        AZURE_APP_CONFIG_CONNECTION_STRING: ${{ inputs.AZURE_APP_CONFIG_CONNECTION_STRING }}
