name: Widget Test Setup
description: Shared setup to install deps (used by test jobs)

inputs:
  node-version:
    description: Node.js version to use
    required: true
  PRIVATE_KEY_FOR_1FE:
    description: Private key for 1FE auth
    required: true
  PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG:
    description: Private key for widget base config
    required: true
  nextVersion:
    description: (Optional) widget version (used by callers for logging etc.)
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout Caller Repo
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn

    - name: Install dependencies
      shell: bash
      run: yarn install --frozen-lockfile
