# .github/actions/update-azure-config/action.yml
name: Update Azure App Configuration
description: Sets the widget version in Azure App Configuration.

inputs:
  environment:
    required: true
    description: "Target environment"
  widgetId:
    required: true
    description: "Widget ID"
  nextVersion:
    required: true
    description: "New version to set"
  AZURE_APP_CONFIG_CONNECTION_STRING:
    required: true
    description: "Connection string"

runs:
  using: "composite"
  steps:
    - name: Set configuration value
      shell: bash
      env:
        WIDGET_ID: ${{ inputs.widgetId }}
        NEXT_VERSION: ${{ inputs.nextVersion }}
        ENVIRONMENT: ${{ inputs.environment }}
        AZURE_APP_CONFIG_CONNECTION_STRING: ${{ inputs.AZURE_APP_CONFIG_CONNECTION_STRING }}
        GH_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      run: |
        echo "Setting AppConfig key: ${ENVIRONMENT}:${WIDGET_ID}"
        az appconfig kv set \
          --key "${ENVIRONMENT}:${WIDGET_ID}" \
          --value "$(jq -n --arg wid "$WIDGET_ID" --arg ver "$NEXT_VERSION" '{widgetId: $wid, version: $ver}')" \
          --content-type application/json \
          --yes \
          --connection-string "${AZURE_APP_CONFIG_CONNECTION_STRING}" \
          --label "${GH_RUN_URL}" # this helps track which run set this value
