# File: docusign/1fe-ci-cd/.github/workflows/ci-widgets.yml
name: Reusable Minimal Widget CI

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '18'
    secrets:
      PRIVATE_KEY_FOR_1FE:
        description: 'SSH private key for accessing docusign/1fe repository'
        required: true
      PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG:
        description: 'SSH private key for accessing docusign/1fe-sample-widget-base-config repository'
        required: true

jobs:
  checkout_and_install:
    name: Checkout and Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Caller's Code
        uses: actions/checkout@v4

      - name: Set up SSH key for docusign/1fe
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_FOR_1FE }}

      - name: Set up SSH key for 1fe-sample-widget-base-config
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG }}

      - name: Add github.com to known_hosts and configure Git URL rewrites
        run: |
          echo "INFO: Adding github.com to known_hosts"
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          echo "INFO: Configuring Git URL rewrites..."
          git config --global url."git@github.com:docusign/1fe.git".insteadOf "https://github.com/docusign/1fe.git"
          git config --global url."git@github.com:docusign/1fe-sample-widget-base-config.git".insteadOf "https://github.com/docusign/1fe-sample-widget-base-config.git"
          
          echo "INFO: Git global config:"
          git config --global --list
          echo "INFO: SSH Agent status (keys loaded):"
          ssh-add -l

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile