name: Reusable Widget Build and Deploy CI

permissions:
  contents: write
  id-token: write

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        type: string
        default: "22"
      base-branch:
        description: "The base branch to commit/tag back to"
        required: false
        type: string
        default: "main"
    secrets:
      AKAMAI_NS_SSH_PRIVATE_KEY:
        required: true
      AZURE_APP_CONFIG_CONNECTION_STRING:
        required: true

jobs:
  build:
    name: Build and Versioning
    runs-on: ubuntu-latest
    outputs:
      widgetId: ${{ steps.call_build_composite.outputs.widgetId }}
      nextVersion: ${{ steps.call_build_composite.outputs.nextVersion }}
    steps:
      - name: Call Widget Build Composite Action
        id: call_build_composite
        uses: docusign/1fe-ci-cd/.github/actions/widget-build@main
        with:
          node-version: ${{ inputs.node-version }}
          base-branch: ${{ inputs.base-branch }}

  upload-integration:
    name: Upload to Akamai (Integration)
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Call Akamai Upload Composite Action
        uses: docusign/1fe-ci-cd/.github/actions/widget-upload-akamai@main
        with:
          widgetId: ${{ needs.build.outputs.widgetId }}
          nextVersion: ${{ needs.build.outputs.nextVersion }}
          akamai-env-path: "integration"
          akamai-ns-ssh-private-key: ${{ secrets.AKAMAI_NS_SSH_PRIVATE_KEY }}

  tests:
    uses: ./.github/workflows/reusable-widget-test.yml
    needs: [build, upload-integration]
    with:
      node-version: ${{ inputs.node-version }}
      widget-id: ${{ needs.build.outputs.widgetId }}
      widget-version: ${{ needs.build.outputs.nextVersion }}

  release-integration:
    name: Release to Integration
    runs-on: ubuntu-latest
    needs: [build, tests, upload-integration]
    if: github.ref_name == inputs.base-branch
    steps:
      - name: Update Azure AppConfig (Integration)
        uses: docusign/1fe-ci-cd/.github/actions/update-azure-config@main
        with:
          environment: integration
          widgetId: ${{ needs.build.outputs.widgetId }}
          nextVersion: ${{ needs.build.outputs.nextVersion }}
          AZURE_APP_CONFIG_CONNECTION_STRING: ${{ secrets.AZURE_APP_CONFIG_CONNECTION_STRING }}

  upload-production:
    name: Upload to Akamai (Production)
    runs-on: ubuntu-latest
    needs: [build, release-integration]
    if: github.ref_name == inputs.base-branch
    steps:
      - name: Upload to Production CDN
        uses: docusign/1fe-ci-cd/.github/actions/widget-upload-akamai@main
        with:
          widgetId: ${{ needs.build.outputs.widgetId }}
          nextVersion: ${{ needs.build.outputs.nextVersion }}
          akamai-env-path: "production"
          akamai-ns-ssh-private-key: ${{ secrets.AKAMAI_NS_SSH_PRIVATE_KEY }}

  test-production:
    name: Test Production
    runs-on: ubuntu-latest
    needs: upload-production
    if: github.ref_name == inputs.base-branch
    steps:
      - name: Run Smoke Tests on Production
        run: echo "Running production smoke tests..."

  approve-production-release:
    name: Approve Production Release
    runs-on: ubuntu-latest
    needs: test-production
    if: github.ref_name == inputs.base-branch
    environment: production-release
    steps:
      - run: echo "Production release approved."

  release-production:
    name: Release to Production
    runs-on: ubuntu-latest
    needs: [build, approve-production-release]
    if: github.ref_name == inputs.base-branch
    steps:
      - name: Update Azure AppConfig (Production)
        uses: docusign/1fe-ci-cd/.github/actions/update-azure-config@main
        with:
          environment: production
          widgetId: ${{ needs.build.outputs.widgetId }}
          nextVersion: ${{ needs.build.outputs.nextVersion }}
          AZURE_APP_CONFIG_CONNECTION_STRING: ${{ secrets.AZURE_APP_CONFIG_CONNECTION_STRING }}