# docusign/1fe-ci-cd/.github/workflows/reusable-build-deploy-ci.yml
name: Reusable Widget Build and Deploy CI
permissions:
  contents: write
  id-token: write
on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        type: string
        default: "22"
      base-branch:
        description: "The base branch to commit/tag back to"
        required: false
        type: string
        default: "main"
    secrets:
      PRIVATE_KEY_FOR_1FE:
        required: true
      PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG:
        required: true
      AKAMAI_NS_SSH_PRIVATE_KEY:
        required: true
      AZURE_APP_CONFIG_CONNECTION_STRING:
        required: true

jobs:
  build:
    name: Build and Versioning # Add name for clarity
    runs-on: ubuntu-latest # This job needs a runner
    outputs: # Job outputs from the composite action's outputs
      widgetId: ${{ steps.call_build_composite.outputs.widgetId }}
      nextVersion: ${{ steps.call_build_composite.outputs.nextVersion }}
    steps: # <--- THIS JOB NOW HAS STEPS TO CALL THE COMPOSITE ACTION
      - name: Call Widget Build Composite Action
        id: call_build_composite # ID for the step calling the composite action
        uses: docusign/1fe-ci-cd/.github/actions/widget-build@main # <--- Call the new composite action
        with:
          node-version: ${{ inputs.node-version }}
          base-branch: ${{ inputs.base-branch }}
          private-key-for-1fe: ${{ secrets.PRIVATE_KEY_FOR_1FE }}
          private-key-for-widget-base-config: ${{ secrets.PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG }}

  tests:
    name: Run All Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Call Widget Test Suite Composite Action
        uses: docusign/1fe-ci-cd/.github/actions/widget-tests@main
        with:
          node-version: ${{ inputs.node-version }}
          nextVersion: ${{ needs.build.outputs.nextVersion }}
          private-key-for-1fe: ${{ secrets.PRIVATE_KEY_FOR_1FE }}
          private-key-for-widget-base-config: ${{ secrets.PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG }}

  upload-integration:
    name: Upload to Akamai (Integration)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == inputs.base-branch
    steps:
      - name: Call Akamai Upload Composite Action
        uses: docusign/1fe-ci-cd/.github/actions/widget-upload-akamai@main
        with:
          widgetId: ${{ needs.build.outputs.widgetId }}
          nextVersion: ${{ needs.build.outputs.nextVersion }}
          akamai-env-path: "integration"
          akamai-ns-ssh-private-key: ${{ secrets.AKAMAI_NS_SSH_PRIVATE_KEY }}

  commit-tag-push:
    name: Commit, Tag, and Push (Git Ops)
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == inputs.base-branch
    steps:
      - name: Call Git Operations Composite Action
        uses: docusign/1fe-ci-cd/.github/actions/git-ops@main
        with:
          widget-id: ${{ needs.build.outputs.widgetId }}
          next-version: ${{ needs.build.outputs.nextVersion }}
          base-branch: ${{ inputs.base-branch }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  release-integration:
    name: Release to Integration
    runs-on: ubuntu-latest
    needs: [build, tests, upload-integration, commit-tag-push]
    if: github.ref_name == inputs.base-branch
    steps:
      - name: Call Azure App Config Update Composite Action
        uses: docusign/1fe-ci-cd/.github/actions/update-azure-config@main
        with:
          environment: integration
          widgetId: ${{ needs.build.outputs.widgetId }}
          nextVersion: ${{ needs.build.outputs.nextVersion }}
          azure-app-config-connection-string: ${{ secrets.AZURE_APP_CONFIG_CONNECTION_STRING }}

  upload-production:
    name: Upload to Akamai (Production)
    runs-on: ubuntu-latest
    needs: [build, release-integration]
    if: github.ref_name == inputs.base-branch
    steps:
      - name: Call Akamai Upload Composite Action
        uses: docusign/1fe-ci-cd/.github/actions/widget-upload-akamai@main
        with:
          widgetId: ${{ needs.build.outputs.widgetId }}
          nextVersion: ${{ needs.build.outputs.nextVersion }}
          akamai-env-path: "production"
          akamai-ns-ssh-private-key: ${{ secrets.AKAMAI_NS_SSH_PRIVATE_KEY }}

  test-production:
    name: Test Production
    runs-on: ubuntu-latest
    needs: upload-production
    if: github.ref_name == inputs.base-branch
    steps:
      - name: Run production smoke tests
        run: echo "Running post-upload tests on production..."

  approve-production-release:
    name: Approve Production Release
    runs-on: ubuntu-latest
    needs: test-production
    if: github.ref_name == inputs.base-branch
    environment: production-release
    steps:
      - run: echo "Production release approved."

  release-production:
    name: Release to Production
    runs-on: ubuntu-latest
    needs: [build, approve-production-release]
    if: github.ref_name == inputs.base-branch
    steps:
      - name: Call Azure App Config Update Composite Action
        uses: docusign/1fe-ci-cd/.github/actions/update-azure-config@main
        with:
          environment: production
          widgetId: ${{ needs.build.outputs.widgetId }}
          nextVersion: ${{ needs.build.outputs.nextVersion }}
          azure-app-config-connection-string: ${{ secrets.AZURE_APP_CONFIG_CONNECTION_STRING }}