# File: docusign/1fe-ci-cd/.github/workflows/ci-widgets.yml
name: Reusable Minimal Widget CI

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '22'
    secrets:
      PRIVATE_KEY_FOR_1FE:
        description: 'SSH private key for accessing docusign/1fe repository'
        required: true
      PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG:
        description: 'SSH private key for accessing docusign/1fe-sample-widget-base-config repository'
        required: true
      AKAMAI_NS_SSH_PRIVATE_KEY: 
              description: 'SSH private key for Akamai NetStorage upload, sourced from Organization Secrets'
              required: true 
        
jobs:
  checkout_and_install:
    name: Checkout and Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Caller's Code
        uses: actions/checkout@v4

      - name: Set up SSH keys for all dependencies
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: | # Use YAML multi-line string to concatenate keys
            ${{ secrets.PRIVATE_KEY_FOR_1FE }}
            ${{ secrets.PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG }}

      - name: Add github.com to known_hosts and configure Git URL rewrites
        run: |
          echo "INFO: Adding github.com to known_hosts"
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          echo "INFO: Configuring Git URL rewrites..."
          git config --global url."git@github.com:docusign/1fe.git".insteadOf "https://github.com/docusign/1fe.git"
          git config --global url."git@github.com:docusign/1fe-sample-widget-base-config.git".insteadOf "https://github.com/docusign/1fe-sample-widget-base-config.git"
          
          echo "INFO: Git global config:"
          git config --global --list
          echo "INFO: SSH Agent status (keys loaded):"
          ssh-add -l # Crucial: check if both keys are listed now

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.8
     
      - name: Extract widgetId, widgetVersion, and nextVersion from package.json
        id: extract_widget_info
        run: |
          widgetId=$(jq -r .name package.json)
          widgetVersion=$(jq -r .version package.json)
          echo "widgetId=$widgetId" >> $GITHUB_ENV
          echo "widgetVersion=$widgetVersion" >> $GITHUB_ENV

          # Determine nextVersion
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            short_sha=$(echo "${GITHUB_SHA}" | cut -c1-7)
            nextVersion="${widgetVersion}-${short_sha}"
            echo "PR run detected. nextVersion set to: $nextVersion"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # Bump patch version by 1
            IFS='.' read -r major minor patch <<< "$widgetVersion"
            if [[ -z "$major" || -z "$minor" || -z "$patch" ]]; then
              echo "Invalid version format: $widgetVersion"
              exit 1
            fi
            patch=$((patch + 1))
            nextVersion="${major}.${minor}.${patch}"
            echo "Merge to main detected. nextVersion bumped to: $nextVersion"
          else
            nextVersion="$widgetVersion"
            echo "Other run detected. nextVersion set to: $nextVersion"
          fi

          echo "nextVersion=$nextVersion" >> $GITHUB_ENV
          echo "Extracted widgetId: $widgetId"
          echo "Extracted widgetVersion: $widgetVersion"
          echo "Persisted nextVersion: $nextVersion"

      - name: Echo widgetId, widgetVersion, and nextVersion
        run: |
          echo "widgetId: $widgetId"
          echo "widgetVersion: $widgetVersion"
          echo "nextVersion: $nextVersion"

      - name: Install Dependencies
        run: |
          echo "INFO: Attempting to install dependencies with Yarn..."
          # Use --immutable as recommended by Yarn 4.x, and --verbose for more detail
          yarn install --no-immutable

      - name: Build the Widget
        run: |
          echo "INFO: Building the widget..."
          CI=true yarn build:widget

          # We want to view the contents of the dist folder and specifically the contents of dist/js/1fe-bundle.js
          echo "INFO: Contents of dist folder:"
          ls -la dist
          echo "INFO: Contents of dist/js:"
          ls -la dist/js
          echo "INFO: Contents of dist/js/1fe-bundle.js:"
          cat dist/js/1fe-bundle.js || echo "1fe-bundle.js does not exist or is empty"

      - name: Upload widget to Akamai NetStorage via rsync
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
        env:
          AKAMAI_NS_SSH_PRIVATE_KEY: ${{ secrets.AKAMAI_NS_SSH_PRIVATE_KEY }}
        run: |
          set -e # Exit immediately if a command exits with a non-zero status.
          
          # ----- Start: Input Validation and Key Setup -----
          if [ -z "$AKAMAI_NS_SSH_PRIVATE_KEY" ]; then
            echo "ERROR: AKAMAI_NS_SSH_PRIVATE_KEY is not set. Skipping upload."
            exit 1
          fi

          echo "INFO: Setting up SSH key for Akamai NetStorage upload..."
          printf "%s\n" "$AKAMAI_NS_SSH_PRIVATE_KEY" > "$HOME/key.pem"
          chmod 600 "$HOME/key.pem"

          if [ ! -s "$HOME/key.pem" ]; then
            echo "ERROR: SSH key file $HOME/key.pem is empty or missing. Skipping upload."
            exit 1
          fi
          # ----- End: Input Validation and Key Setup -----

          src_dir="dist/"
          # Ensure widgetId and nextVersion are correctly populated from GITHUB_ENV
          dest_dir="integration/widgets/$widgetId/$nextVersion/" 
          
          # ----- Start: Enhanced Debugging Section -----
          echo "--- Runner Environment Debugging ---"
          echo "Runner current working directory: $(pwd)"
          echo "Widget ID: $widgetId"
          echo "Next Version: $nextVersion"
          echo "Source directory variable (\$src_dir): $src_dir"
          echo "Destination directory variable (\$dest_dir): $dest_dir"
          
          echo "--- Source Directory Contents ---"
          echo "Listing contents of source directory '$src_dir':"
          ls -la "$src_dir"
          
          echo "--- SSH Key File Check ---"
          echo "Checking key file '$HOME/key.pem':"
          ls -l "$HOME/key.pem"
          echo "Attempting to get fingerprint of key.pem (can fail for some key formats but key might still be valid):"
          ssh-keygen -lf "$HOME/key.pem" || echo "INFO: ssh-keygen -lf failed (not necessarily an error)."

          REMOTE_HOST="sshacs@1fe.rsync.upload.akamai.com"
          SSH_OPTS="-o StrictHostKeyChecking=no -oBatchMode=yes -i $HOME/key.pem" 

          echo "--- Remote Server Path Inspection (Before Rsync) ---"
          echo "INFO: Attempting to list base directory for user 'sshacs' on Akamai:"
          ssh $SSH_OPTS "$REMOTE_HOST" "ls -la" || echo "WARNING: Failed to list base directory on remote."
          
          echo "INFO: Attempting to list components of destination path '$dest_dir' on remote:"
          widget_id_base_path=""
          if [[ "$widgetId" == *"/"* ]]; then
            widget_id_base_path="${widgetId%/*}"
          fi

          path_to_check="integration"
          echo "Checking remote: $path_to_check"
          ssh $SSH_OPTS "$REMOTE_HOST" "ls -ld '$path_to_check'" || echo "INFO: '$path_to_check' does not exist or is not accessible."
          
          path_to_check="integration/widgets"
          echo "Checking remote: $path_to_check"
          ssh $SSH_OPTS "$REMOTE_HOST" "ls -ld '$path_to_check'" || echo "INFO: '$path_to_check' does not exist or is not accessible."
          
          if [ -n "$widget_id_base_path" ]; then
            path_to_check="integration/widgets/$widget_id_base_path"
            echo "Checking remote: $path_to_check"
            ssh $SSH_OPTS "$REMOTE_HOST" "ls -ld '$path_to_check'" || echo "INFO: '$path_to_check' does not exist or is not accessible."
          fi
          
          path_to_check="integration/widgets/$widgetId"
          echo "Checking remote: $path_to_check"
          ssh $SSH_OPTS "$REMOTE_HOST" "ls -ld '$path_to_check'" || echo "INFO: '$path_to_check' does not exist or is not accessible."

          path_to_check="integration/widgets/$widgetId/$nextVersion" 
          echo "Checking remote (full destination without trailing slash): $path_to_check"
          ssh $SSH_OPTS "$REMOTE_HOST" "ls -ld '$path_to_check'" || echo "INFO: '$path_to_check' does not exist or is not accessible."
          # ----- End: Enhanced Debugging Section -----

          echo "--- Rsync Upload Attempt ---"
          # Base rsync command: archive, verbose, verbose, make-path
          RSYNC_CMD="rsync -avv --mkpath" 

          # Conditional Dry Run for PRs
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "INFO: This is a Pull Request. Adding --dry-run to rsync."
            RSYNC_CMD="$RSYNC_CMD --dry-run"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "INFO: This is a push to the main branch. Rsync will upload without deleting."
            # No --delete flag is added here, respecting your requirement.
          fi

          echo "INFO: Preparing to execute: $RSYNC_CMD -e \"ssh $SSH_OPTS\" \"$src_dir\" \"$REMOTE_HOST:'$dest_dir'\""
          
          $RSYNC_CMD \
            -e "ssh $SSH_OPTS" \
            "$src_dir" \
            "$REMOTE_HOST:'$dest_dir'"
          # The script will exit here if rsync fails, due to 'set -e'

          echo "INFO: Rsync command finished successfully."
          echo "INFO: Upload complete. Cleaning up SSH key."
          shred -u "$HOME/key.pem" || rm -f "$HOME/key.pem"


