# File: docusign/1fe-ci-cd/.github/workflows/ci-widgets.yml
name: Reusable Minimal Widget CI

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '22'
    secrets:
      PRIVATE_KEY_FOR_1FE:
        description: 'SSH private key for accessing docusign/1fe repository'
        required: true
      PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG:
        description: 'SSH private key for accessing docusign/1fe-sample-widget-base-config repository'
        required: true

jobs:
  checkout_and_install:
    name: Checkout and Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Caller's Code
        uses: actions/checkout@v4

      - name: Set up SSH keys for all dependencies
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: | # Use YAML multi-line string to concatenate keys
            ${{ secrets.PRIVATE_KEY_FOR_1FE }}
            ${{ secrets.PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG }}

      - name: Add github.com to known_hosts and configure Git URL rewrites
        run: |
          echo "INFO: Adding github.com to known_hosts"
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          echo "INFO: Configuring Git URL rewrites..."
          git config --global url."git@github.com:docusign/1fe.git".insteadOf "https://github.com/docusign/1fe.git"
          git config --global url."git@github.com:docusign/1fe-sample-widget-base-config.git".insteadOf "https://github.com/docusign/1fe-sample-widget-base-config.git"
          
          echo "INFO: Git global config:"
          git config --global --list
          echo "INFO: SSH Agent status (keys loaded):"
          ssh-add -l # Crucial: check if both keys are listed now

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          registry-url: https://registry.npmjs.org/
          cache: 'yarn'

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.8
     
      - name: Extract widgetId, widgetVersion, and nextVersion from package.json
        id: extract_widget_info
        run: |
          widgetId=$(jq -r .name package.json)
          widgetVersion=$(jq -r .version package.json)
          echo "widgetId=$widgetId" >> $GITHUB_ENV
          echo "widgetVersion=$widgetVersion" >> $GITHUB_ENV

          # Determine nextVersion
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            short_sha=$(echo "${GITHUB_SHA}" | cut -c1-7)
            nextVersion="${widgetVersion}-${short_sha}"
            echo "PR run detected. nextVersion set to: $nextVersion"
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            # Bump patch version by 1
            IFS='.' read -r major minor patch <<< "$widgetVersion"
            if [[ -z "$major" || -z "$minor" || -z "$patch" ]]; then
              echo "Invalid version format: $widgetVersion"
              exit 1
            fi
            patch=$((patch + 1))
            nextVersion="${major}.${minor}.${patch}"
            echo "Merge to main detected. nextVersion bumped to: $nextVersion"
          else
            nextVersion="$widgetVersion"
            echo "Other run detected. nextVersion set to: $nextVersion"
          fi

          echo "nextVersion=$nextVersion" >> $GITHUB_ENV
          echo "Extracted widgetId: $widgetId"
          echo "Extracted widgetVersion: $widgetVersion"
          echo "Persisted nextVersion: $nextVersion"

      - name: Echo widgetId, widgetVersion, and nextVersion
        run: |
          echo "widgetId: $widgetId"
          echo "widgetVersion: $widgetVersion"
          echo "nextVersion: $nextVersion"

      - name: Install Dependencies
        run: |
          echo "INFO: Attempting to install dependencies with Yarn..."
          # Use --immutable as recommended by Yarn 4.x, and --verbose for more detail
          yarn install --no-immutable

      - name: Build the Widget
        run: |
          echo "INFO: Building the widget..."
          CI=true yarn build:widget

          # We want to view the contents of the dist folder and specifically the contents of dist/js/1fe-bundle.js
          echo "INFO: Contents of dist folder:"
          ls -la dist
          echo "INFO: Contents of dist/js:"
          ls -la dist/js
          echo "INFO: Contents of dist/js/1fe-bundle.js:"
          cat dist/js/1fe-bundle.js || echo "1fe-bundle.js does not exist or is empty"

      - name: Upload widget to Akamai NetStorage via rsync
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
        env:
          AKAMAI_NS_SSH_PRIVATE_KEY: ${{ secrets.AKAMAI_NS_SSH_PRIVATE_KEY }}
        run: |
          set -e
          if [ -z "$AKAMAI_NS_SSH_PRIVATE_KEY" ]; then
            echo "ERROR: AKAMAI_NS_SSH_PRIVATE_KEY is not set. Skipping upload."
            exit 1
          fi

          echo "Setting up SSH key for Akamai NetStorage upload..."
          echo "$AKAMAI_NS_SSH_PRIVATE_KEY" > $HOME/key.pem
          chmod 600 $HOME/key.pem

          if [ ! -s "$HOME/key.pem" ]; then
            echo "ERROR: SSH key file $HOME/key.pem is empty or missing. Skipping upload."
            exit 1
          fi

          src_dir="dist/"
          dest_dir="integration/widgets/$widgetId/$nextVersion/"
          echo "Uploading $src_dir to Akamai NetStorage at $dest_dir"

          rsync -avv \
            -e "ssh -o StrictHostKeyChecking=no -i $HOME/key.pem" \
            "$src_dir" \
            "sshacs@1fe.rsync.upload.akamai.com:$dest_dir" \
          || echo "WARNING: rsync finished with a non-zero exit code ($?). Please check logs above for any errors."

          echo "Upload complete. Cleaning up SSH key."
          shred -u $HOME/key.pem || rm -f $HOME/key.pem



