name: Reusable Widget Rollback CI

on:
  workflow_call:
    inputs:
      target-version:
        required: true
        type: string
      environment:
        required: true
        type: string
      caller-repo-ref:
        required: true
        type: string
      caller-repo:
        required: true
        type: string
    secrets:
      AZURE_APP_CONFIG_CONNECTION_STRING:
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  check-and-prepare:
    name: Validate & Extract Info
    runs-on: ubuntu-latest
    outputs:
      widgetId: ${{ steps.get_widget_id.outputs.widgetId }}
      assetExists: ${{ steps.check_cdn.outputs.assetExists }}
    steps:
      - name: Checkout caller repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.caller-repo }}
          ref: ${{ inputs.caller-repo-ref }}
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"

      - name: Get Widget ID
        id: get_widget_id
        run: echo "widgetId=$(npm pkg get name | tr -d '"')" >> $GITHUB_OUTPUT

      - name: Check CDN Asset Exists
        id: check_cdn
        uses: docusign/1fe-ci-cd/.github/actions/check-cdn-asset@main
        with:
          widgetId: ${{ steps.get_widget_id.outputs.widgetId }}
          targetVersion: ${{ inputs.target-version }}
          environment: ${{ inputs.environment }}

  update-config:
    name: Update Azure App Config
    needs: check-and-prepare
    if: ${{ needs.check-and-prepare.outputs.assetExists == 'true' }}
    uses: docusign/1fe-ci-cd/.github/workflows/reusable-update-azure-config.yml@main
    with:
      environment: ${{ inputs.environment }}
      widgetId: ${{ needs.check-and-prepare.outputs.widgetId }}
      nextVersion: ${{ inputs.target-version }}
    secrets:
      AZURE_APP_CONFIG_CONNECTION_STRING: ${{ secrets.AZURE_APP_CONFIG_CONNECTION_STRING }}
