name: Widget Test Jobs

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        required: true
      widget-version:
        type: string
        required: false
      widget-id:
        type: string
        required: false

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: docusign/1fe-ci-cd/.github/actions/widget-test-setup@main
        with:
          node-version: ${{ inputs.node-version }}
      - run: yarn lint

  unit-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: docusign/1fe-ci-cd/.github/actions/widget-test-setup@main
        with:
          node-version: ${{ inputs.node-version }}
      - run: yarn test

  e2e-tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - uses: docusign/1fe-ci-cd/.github/actions/widget-test-setup@main
        with:
          node-version: ${{ inputs.node-version }}
      - run: |
          echo "Running Playwright for version ${{ inputs.widget-version }}"
          npx playwright install --with-deps
          WIDGET_VERSION=${{ inputs.widget-version }} DEBUG=pw:api npx playwright test
