name: Reusable Widget Tests

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      nextVersion:
        required: true
        type: string
    secrets:
      PRIVATE_KEY_FOR_1FE:
        required: true
      PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG:
        required: true

jobs:
  setup:
    name: Setup Test Environment
    runs-on: ubuntu-latest
    outputs:
      nextVersion: ${{ inputs.nextVersion }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn
      - run: yarn install --frozen-lockfile

  lint:
    name: Run Linting
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - run: yarn lint

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - run: yarn test

  e2e-tests:
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "Running Playwright for version ${{ needs.setup.outputs.nextVersion }}"
          yarn test:e2e
