# docusign/1fe-ci-cd/.github/workflows/reusable-widget-tests.yml
name: Reusable - Widget Tests
permissions:
  contents: read # Only needs to read code
on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        type: string
        default: "22"
    secrets: # Needed if test dependencies are from private repos
      PRIVATE_KEY_FOR_1FE:
        required: true
      PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG:
        required: true
jobs:
  lint-test:
    name: Lint Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up dependency SSH keys
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.PRIVATE_KEY_FOR_1FE }}
            ${{ secrets.PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --no-immutable
      - name: Run Linting
        run: yarn lint

  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    continue-on-error: true # Consider removing for stricter CI
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up dependency SSH keys
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.PRIVATE_KEY_FOR_1FE }}
            ${{ secrets.PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --no-immutable
      - name: Run Unit Tests
        run: yarn test

  contract-test:
    name: Contract Test
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up dependency SSH keys
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.PRIVATE_KEY_FOR_1FE }}
            ${{ secrets.PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --no-immutable
      - name: Run Contract Tests
        run: echo "Running contract tests..."

  playwright-test:
    name: Playwright E2E Test
    runs-on: ubuntu-latest
    continue-on-error: true # Consider removing for stricter CI
    # No 'needs: build' here directly, the build artifact will be downloaded by a different job if needed.
    # This job focuses on running tests on *current* code, assuming a built artifact might be for later stages.
    # If Playwright tests *require* the built artifact for execution, you would add a 'download-artifact' step here.
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up dependency SSH keys
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: |
            ${{ secrets.PRIVATE_KEY_FOR_1FE }}
            ${{ secrets.PRIVATE_KEY_FOR_WIDGET_BASE_CONFIG }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --no-immutable
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      # IMPORTANT: If your Playwright tests need WIDGET_VERSION from the build,
      # you'd need to pass it as an input to this reusable workflow.
      # For now, it defaults to the test file's logic.
      - name: Run Playwright tests
        run: npx playwright test